// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEwpj9_Ykv7JtLzRaA_SDalKUeMz1fHI',
    appId: '1:485949359931:web:05496e5999309c46f5d91e',
    messagingSenderId: '485949359931',
    projectId: 'thedevilwear-bc43b',
    authDomain: 'thedevilwear-bc43b.firebaseapp.com',
    storageBucket: 'thedevilwear-bc43b.appspot.com',
    measurementId: 'G-P1DXX95SN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDlUeSms6rsGvAqnOwZW0TGJW0Az1T9wk',
    appId: '1:485949359931:android:2ad99325ae92d8edf5d91e',
    messagingSenderId: '485949359931',
    projectId: 'thedevilwear-bc43b',
    storageBucket: 'thedevilwear-bc43b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCymnjBt1bTxtIMkIjzBiwhu4uhAaM3TKE',
    appId: '1:485949359931:ios:dda61ac29bf57394f5d91e',
    messagingSenderId: '485949359931',
    projectId: 'thedevilwear-bc43b',
    storageBucket: 'thedevilwear-bc43b.appspot.com',
    iosClientId: '485949359931-5evrret92911v3416q5jeth1l8pq5rp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocktailRecipeGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCymnjBt1bTxtIMkIjzBiwhu4uhAaM3TKE',
    appId: '1:485949359931:ios:70a944d052ab0236f5d91e',
    messagingSenderId: '485949359931',
    projectId: 'thedevilwear-bc43b',
    storageBucket: 'thedevilwear-bc43b.appspot.com',
    iosClientId: '485949359931-4a8rvri22i32sje0jmup8p3gqd3bm6s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocktailRecipeGenerator.RunnerTests',
  );
}
